// apps/web/src/lib/components/workspace/settings/ExpirationReminderEditor.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import type { ExpirationReminderPolicy } from '$lib/domain/notification';
  import { safeWorkspaceErrorMessage } from '$lib/application/workspaceSafeError';
  import { Checkbox } from '$lib/components/ui/checkbox/index.js';
  import { Input } from '$lib/components/ui/input/index.js';
  import { Label } from '$lib/components/ui/label/index.js';
  import * as Button from '$lib/components/ui/button/index.js';

  let { initialPolicy, inheritedPolicy, onSave }: {
    initialPolicy: ExpirationReminderPolicy | null;
    inheritedPolicy?: ExpirationReminderPolicy;
    onSave: (policy: ExpirationReminderPolicy | null) => Promise<void>;
  } = $props();
  const id = $props.id();
  const initial = untrack(() => initialPolicy ?? inheritedPolicy);
  if (!initial) throw new Error('A reminder policy is required.');
  let inherit = $state(untrack(() => initialPolicy === null));
  let draft = $state({ ...initial });
  let days = $state(String(initial.advanceDays));
  let saving = $state(false);
  let error = $state('');
  let saved = $state(false);
  let displayed = $derived(inherit && inheritedPolicy ? inheritedPolicy : draft);
  let validDays = $derived(/^\d+$/.test(days) && Number(days) <= 3650);
  let controlsDisabled = $derived(saving || inherit);

  function changed() { saved = false; error = ''; }
  async function save(event: SubmitEvent) {
    event.preventDefault();
    if (saving || (!inherit && !validDays)) return;
    saving = true; error = ''; saved = false;
    try {
      await onSave(inherit ? null : { ...draft, advanceDays: Number(days) });
      saved = true;
    } catch (caught) {
      error = safeWorkspaceErrorMessage(caught, 'Reminders could not be saved. Your changes are still here. Try again.');
    } finally { saving = false; }
  }
</script>

<form onsubmit={save} aria-label="Expiration reminders">
  {#if inheritedPolicy}
    <Label class="setting"><Checkbox checked={inherit} disabled={saving} onchange={(event) => { inherit = event.currentTarget.checked; changed(); }} />Use inventory defaults</Label>
    <p>{inherit ? 'Inherited from your inventory settings.' : 'Custom settings for this asset type.'}</p>
  {:else}
    <p>Your defaults for this inventory. Asset types with custom settings can still send reminders when these defaults are off.</p>
  {/if}
  <Label class="setting"><Checkbox checked={displayed.enabled} disabled={controlsDisabled} onchange={(event) => { draft.enabled = event.currentTarget.checked; changed(); }} />Enable expiration reminders</Label>
  <Label class="setting"><Checkbox checked={displayed.upcoming} disabled={controlsDisabled} onchange={(event) => { draft.upcoming = event.currentTarget.checked; changed(); }} />Notify before expiration</Label>
  <div class="days">
    <Label for={`${id}-days`}>Days before expiration</Label>
    <Input id={`${id}-days`} type="number" min={0} max={3650} step={1} value={inherit ? displayed.advanceDays : days} disabled={controlsDisabled}
      aria-invalid={!inherit && !validDays} aria-describedby={`${id}-help`}
      oninput={(event) => { days = event.currentTarget.value; changed(); }} />
    <p id={`${id}-help`}>{!inherit && !validDays ? 'Enter a whole number from 0 to 3650.' : 'Calendar days before the expiration date ends.'}</p>
  </div>
  <Label class="setting"><Checkbox checked={displayed.expired} disabled={controlsDisabled} onchange={(event) => { draft.expired = event.currentTarget.checked; changed(); }} />Notify when expired</Label>
  {#if error}<p role="alert">{error}</p>{/if}
  {#if saved}<p role="status">Reminders saved.</p>{/if}
  <Button.Root type="submit" disabled={saving || (!inherit && !validDays)}>{saving ? 'Saving…' : 'Save reminders'}</Button.Root>
</form>

<style>
  form { display: grid; gap: 1rem; }
  form :global(.setting) { display: flex; align-items: center; gap: 0.75rem; min-height: 2.75rem; cursor: pointer; }
  .days { display: grid; gap: 0.5rem; }
  p { color: var(--muted-foreground); font-size: 0.875rem; }
  [role='alert'] { color: var(--destructive); }
</style>

// apps/mobile/src/ui/components/ExpirationReminderEditor.tsx
import { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { ExpirationReminderPolicy } from '../../domain/notifications/Notification';
import { NotificationFailure } from '../../application/notifications/NotificationFailure';
import { useAppearancePalette } from '../theme/AppearanceContext';
import { radius, spacing } from '../theme/tokens';
import { AppSwitchField } from './AppSwitchField';
import { AppTextInput } from './AppTextInput';

export function ExpirationReminderEditor({ initialPolicy, inheritedPolicy, disabled = false, onSave }: {
  readonly initialPolicy: ExpirationReminderPolicy | null;
  readonly inheritedPolicy?: ExpirationReminderPolicy;
  readonly disabled?: boolean;
  readonly onSave: (value: ExpirationReminderPolicy | null) => Promise<void>;
}) {
  const colors = useAppearancePalette();
  const initial = initialPolicy ?? inheritedPolicy;
  if (!initial) throw new Error('A reminder policy is required.');
  const [inherit, setInherit] = useState(initialPolicy === null);
  const [draft, setDraft] = useState({ ...initial });
  const [days, setDays] = useState(String(initial.advanceDays));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);
  const pending = useRef(false);
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const displayed = inherit && inheritedPolicy ? inheritedPolicy : draft;
  const valid = /^\d+$/.test(days) && Number(days) <= 3650;
  const locked = disabled || saving || inherit;
  function changed() { setSaved(false); setError(''); }
  function toggle(field: 'enabled' | 'upcoming' | 'expired', value: boolean) {
    if (locked) return;
    setDraft((previous) => ({ ...previous, [field]: value })); changed();
  }
  async function save() {
    if (disabled || pending.current || (!inherit && !valid)) return;
    pending.current = true; setSaving(true); setError(''); setSaved(false);
    try {
      await onSave(inherit ? null : { ...draft, advanceDays: Number(days) });
      if (mounted.current) setSaved(true);
    } catch (caught) {
      if (mounted.current) setError(caught instanceof NotificationFailure ? caught.message : 'Reminders could not be saved. Your changes are still here. Try again.');
    } finally { pending.current = false; if (mounted.current) setSaving(false); }
  }
  return <View style={styles.form}>
    {inheritedPolicy ? <>
      <AppSwitchField label="Use inventory defaults" value={inherit} disabled={disabled || saving} onValueChange={(value) => { if (disabled || saving) return; setInherit(value); changed(); }} />
      <Text style={{ color: colors.textMuted }}>{inherit ? 'Inherited from your inventory settings.' : 'Custom settings for this asset type.'}</Text>
    </> : <Text style={{ color: colors.textMuted }}>Your inventory defaults. Asset types with custom settings can still send reminders when these defaults are off.</Text>}
    <AppSwitchField label="Enable expiration reminders" value={displayed.enabled} disabled={locked} onValueChange={(value) => toggle('enabled', value)} />
    <AppSwitchField label="Notify before expiration" value={displayed.upcoming} disabled={locked} onValueChange={(value) => toggle('upcoming', value)} />
    <Text style={{ color: colors.text }}>Days before expiration</Text>
    <AppTextInput accessibilityLabel="Days before expiration" keyboardType="number-pad" editable={!locked} value={inherit ? String(displayed.advanceDays) : days} onChangeText={(value) => { if (locked) return; setDays(value); changed(); }} style={[styles.input, { color: colors.text, borderColor: colors.controlBorder }]} />
    {!inherit && !valid ? <Text accessibilityRole="alert" style={{ color: colors.danger }}>Enter a whole number from 0 to 3650.</Text> : null}
    <AppSwitchField label="Notify when expired" value={displayed.expired} disabled={locked} onValueChange={(value) => toggle('expired', value)} />
    {error ? <Text accessibilityRole="alert" style={{ color: colors.danger }}>{error}</Text> : null}
    {saved ? <Text accessibilityLiveRegion="polite" style={{ color: colors.textMuted }}>Reminders saved.</Text> : null}
    <Pressable accessibilityRole="button" accessibilityLabel="Save reminders" accessibilityState={{ disabled: disabled || saving || (!inherit && !valid), busy: saving }} disabled={disabled || saving || (!inherit && !valid)} onPress={save} style={[styles.button, { borderColor: colors.controlBorder }]}>
      <Text style={{ color: colors.text }}>{saving ? 'Saving…' : 'Save reminders'}</Text>
    </Pressable>
  </View>;
}
const styles = StyleSheet.create({
  form: { gap: spacing.sm },
  input: { minHeight: 44, borderWidth: 1, borderRadius: radius.md, padding: spacing.sm },
  button: { minHeight: 44, borderWidth: 1, borderRadius: radius.md, padding: spacing.sm, justifyContent: 'center', alignItems: 'center' }
});
